INSERT INTO interview_questions (created_at, updated_at, category, content, is_public)
VALUES (NOW(6), NOW(6), 'PERSONAL', '내가 생각하는 나의 장점과 단점', 1),
       (NOW(6), NOW(6), 'PERSONAL', '현재 하고 있는 일', 1),
       (NOW(6), NOW(6), 'PERSONAL', '나의 평일/주말 생활 패턴', 1),
       (NOW(6), NOW(6), 'PERSONAL', '일상에서 느끼는 나의 소소한 행복', 1),
       (NOW(6), NOW(6), 'PERSONAL', '내가 생각하는 나의 반전 매력', 1),
       (NOW(6), NOW(6), 'PERSONAL', '나만의 스트레스 해소 방법', 1),
       (NOW(6), NOW(6), 'PERSONAL', '좋아하는 음식/싫어하는 음식', 1),
       (NOW(6), NOW(6), 'PERSONAL', '배우고 싶은 분야/언어', 1),
       (NOW(6), NOW(6), 'PERSONAL', '10년 후 나의 모습', 1),
       (NOW(6), NOW(6), 'PERSONAL', '요즘 하고 있는 자기관리', 1),
       (NOW(6), NOW(6), 'PERSONAL', '내 삶의 우선 순위(나, 가족, 연인, 친구, 커리어 등)', 1),

       (NOW(6), NOW(6), 'SOCIAL', '남사친/여사친에 대한 나의 생각', 1),
       (NOW(6), NOW(6), 'SOCIAL', '나의 인간관계 스타일', 1),
       (NOW(6), NOW(6), 'SOCIAL', '호감을 느끼는 사람의 유형/타입', 1),
       (NOW(6), NOW(6), 'SOCIAL', '인간관계에서 가장 중요한 것', 1),
       (NOW(6), NOW(6), 'SOCIAL', '썸에 대한 나의 생각(기준, 적정 기간, 스킨십)', 1),
       (NOW(6), NOW(6), 'SOCIAL', '사랑하는 사람이 생겼을 때 결혼에 대한 고려', 1),
       (NOW(6), NOW(6), 'SOCIAL', '내 주변의 이성 친구들', 1),
       (NOW(6), NOW(6), 'SOCIAL', '나는 인싸?/아싸?', 1),
       (NOW(6), NOW(6), 'SOCIAL', '매일 연락하고 지내는 사람의 수', 1),
       (NOW(6), NOW(6), 'SOCIAL', '주변 사람들이 말하는 나의 모습', 1),

       (NOW(6), NOW(6), 'ROMANTIC', '추구하는 만남 횟수와 연락 빈도', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '내가 연인을 사랑하는 방식', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인에게 바라는 점', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인 관계에서 가장 중요하다고 생각하는 것', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '선호하는 데이트 스타일', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인 사이의 갈등 해소 방법', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인에게만 보여줄 수 있는 나의 모습', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인을 위해 내가 할 수 있는 것', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인에게 들려주고 싶은 노래', 1),
       (NOW(6), NOW(6), 'ROMANTIC', '연인과 함께 가보고 싶은 장소', 1);
